# docker integration tests
sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t monxas/docker-react

script:
  - docker run -e CI=true monxas/docker-react npm run test